# Generated by Django 3.2 on 2022-05-19 23:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de Cliente')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccón')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_tracking', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Motivo_Fallo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_fallo', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('posicion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(max_length=100, unique=True, verbose_name='N° Tracking')),
                ('direccion_des', models.CharField(max_length=200, verbose_name='Dirección Destino')),
                ('telefono_des', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('nombre_des', models.CharField(max_length=200, unique=True, verbose_name='Nombre Destino')),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Altura')),
                ('tipo_paquete', models.CharField(max_length=25)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Base.cliente', verbose_name='Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Base.estado_tracking', verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=150)),
                ('Motivo_Fallo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Base.motivo_fallo')),
                ('num_platilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Base.plantilla')),
                ('paquete', models.ManyToManyField(to='App_Base.Paquete')),
            ],
        ),
    ]
