# Generated by Django 3.2.12 on 2022-05-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
