# Generated by Django 3.2.12 on 2022-05-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0003_auto_20220521_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso'),
        ),
    ]
