# Generated by Django 3.2 on 2022-05-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0004_alter_paquete_peso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Motivo_Fallo',
            new_name='motivo_fallo',
        ),
        migrations.AlterField(
            model_name='paquete',
            name='tipo_paquete',
            field=models.CharField(editable=False, max_length=25),
        ),
    ]
