# Generated by Django 3.2 on 2022-05-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0006_auto_20220521_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='num_platilla',
            new_name='num_plantilla',
        ),
    ]
